name: generate and deploy static content using 11ty
on:
  - push
  - workflow_dispatch
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'production'
      ELEVENTY_pathPrefix: '/jencysamuel.com'
    steps:
      - name: 'get repo'
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: 'setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: 'get npm cache dir'
        id: cache-dir
        run: printf '::set-output name=path::%s' $(npm config get cache)

      - name: 'get cached node_modules'
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.path }}
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-cache-

      - name: 'install dependencies'
        # include `dev` because omitted
        #   when NODE_ENV=production
        run: npm ci --include dev

      - name: 'build'
        run: npm run build

      - name: 'upload artificat'
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    if: github.ref_name == 'www-11ty'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 'deploy to GitHub Pages'
        id: deploy
        uses: actions/deploy-pages@v1

